import "./globals.css";
import type { Metadata } from "next";
import Head from "next/head";
import Link from "next/link";

import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Navbar Component",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <Link rel="preconnect" href="https://fonts.googleapis.com" />
        <Link rel="preconnect" href="https://fonts.gstatic.com" />
        <Link
          href="https://fonts.googleapis.com/css2?family=Delius&family=Inter:wght@400;500;600;700&family=Mukta:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&family=Roboto:wght@400;500;700&family=Sacramento&family=Source+Code+Pro:wght@400;500;600;700&family=Work+Sans:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className="bg-bodyColor font-body">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
